//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carwash.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class appointments
    {
        public int appointment_id { get; set; }
        public string name { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime date { get; set; }
        public System.TimeSpan time { get; set; }
        public int user_id { get; set; }
        public int service_id { get; set; }
        public string site { get; set; }
    
        public virtual service service { get; set; }
        public virtual users users { get; set; }
    }
}
