//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carwash.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Binnacle
    {
        public int idBinnacle { get; set; }
        [Required(ErrorMessage = "El nombre es obligatorio.")]
        public string type { get; set; }
        [Required(ErrorMessage = "La descripcion es obligatorio.")]

        public string description { get; set; }
        [Required(ErrorMessage = "El monto es obligatorio.")]

        public Nullable<decimal> amount { get; set; }
    }
}
