//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carwash.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class carwashEntities : DbContext
    {
        public carwashEntities()
            : base("name=carwashEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<appointments> appointments { get; set; }
        public virtual DbSet<Binnacle> Binnacle { get; set; }
        public virtual DbSet<notifications> notifications { get; set; }
        public virtual DbSet<product_stock> product_stock { get; set; }
        public virtual DbSet<roles> roles { get; set; }
        public virtual DbSet<service> service { get; set; }
        public virtual DbSet<users> users { get; set; }
        public virtual DbSet<Vendors> Vendors { get; set; }
    }
}
